// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsrrtjwyjgyalpzknnsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcnJ0and5amd5YWxwemtubnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTE5MTUsImV4cCI6MjA2Njc4NzkxNX0.oQ0hH06gh6rph7fOdoXIHo80gyikPC0I6sPVBv0Z40Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});